### PR TITLE
Create String as an input from the user using %s and %c . Compare them

### PR DESCRIPTION
**Pull request by Shrutijain005**
Here we have used strcmp to compare two strings .

Fixes #

## Proposed Changes

-
-
-

### CODE REVIEW

**Review by aravindvnair99 — CHANGES_REQUESTED** [review]
@Shrutijain005 Thanks for your contribution! Could you please sign the commit as well? You can perform the two steps mentioned here: https://github.com/aravindvnair99/C/pull/15/checks?check_run_id=1191342053

**Comment by aravindvnair99** [comment]
@Shrutijain005 It would be better to accept two strings as a whole rather than taking the second one character by character.

**Comment by Shrutijain005** [comment]
> @Shrutijain005 It would be better to accept two strings as a whole rather than taking the second one character by character
But we're using %c so that we can see that the same thing can be implemented by both % c and %s ,but using %s is easier.

**Comment by Shrutijain005** [comment]
> @Shrutijain005 Thanks for your contribution! Could you please sign the commit as well? You can perform the two steps mentioned here: https://github.com/aravindvnair99/C/pull/15/checks?check_run_id=1191342053

It's not happening , should i make a new pull request.

**Comment by aravindvnair99** [comment]
> > @Shrutijain005 Thanks for your contribution! Could you please sign the commit as well? You can perform the two steps mentioned here: https://github.com/aravindvnair99/C/pull/15/checks?check_run_id=1191342053
> 
> It's not happening , should i make a new pull request.

@Shrutijain005 You don't have to make a new pull request. You can make the necessary changes here as well. If you need help, let me know and I'll guide you.

**Comment by aravindvnair99** [comment]
@Shrutijain005 Could you switch both to %s instead of %c? Because having both can lead to confusions for beginners trying out the program.

**Comment by aravindvnair99** [comment]
@Shrutijain005 Closing due to inactivity. Feel free to reopen the pull request.

**Pull request closed without merging**
