### PR TITLE
Max Min of an Array (Tournament Method)

### PR DESCRIPTION
**Pull request by abirbhattacharya82**
## Proposed Changes

- Added a new C program which finds the minimum and maximum of an array using tournament method.

### CODE REVIEW

**Review by aravindvnair99 — CHANGES_REQUESTED** [review]
Hey @abirbhattacharya82!

Thanks for your contribution! This is a nice thing to add. I did notice your code doesn't validate the input. Could you fix that? Once you are done, I shall merge this PR. To give you more context:
```console
Enter the Size of the array=> a23
Enter the Elements in the Array
Maximum=> 0
Minimum=> 0
```
This is just one example. The same applies to other inputs as well. Let me know if you didn't understand and I can explain more.

**Comment by abirbhattacharya82** [comment]
Hi @aravindvnair99 , I didn't get you, can you explain the issue a little bit?

**Comment by aravindvnair99** [comment]
> Hi @aravindvnair99 , I didn't get you, can you explain the issue a little bit?

Sure @abirbhattacharya82, input validation is the process of verifying the input is indeed what we are expecting and not anything else. This not only prevents unexpected errors but, in most cases (big production-level applications), also prevent security risks. It is always necessary to validate user input than accept it simply and this also is a safer way to code.

For example, in my [previous message](https://github.com/aravindvnair99/C/pull/23#pullrequestreview-686718668), you can see I gave the input as letters instead of the number and the program accepted it instead of asking me to enter again. If input validation was instead implemented, what would have happened is that it would have checked to ensure it is indeed a number before continuing further and if not asking the user to enter again.

Similarly, for other inputs as well, proper validation should be done. I would suggest you give these 2 a read:

- [C input validation best practices](https://www.google.com/search?q=c+input+validation+best+practices)
- [C input validation](https://www.google.com/search?q=c+input+validation)

Once you have understood why we need to do this and how to do it, you can try implementing the same and I will review your code again. Feel free to keep pushing commits or tag me anytime.

**Comment by abirbhattacharya82** [comment]
@aravindvnair99 thanks for telling me about this. What I understood is that I need to check if the input provided by the user is a valid one or not. For example,
`int x;
scanf("%d",&x);
`
now here the user can provide inputs like 'a' or -2 or 0 which is not a valid one for defining the size of an array. So, what I understood is that every time there is an input I have to check if its the desired kind of output required or not.
Is that so???

**Comment by aravindvnair99** [comment]
> @aravindvnair99 thanks for telling me about this. What I understood is that I need to check if the input provided by the user is a valid one or not. For example,
> `int x; scanf("%d",&x); `
> now here the user can provide inputs like 'a' or -2 or 0 which is not a valid one for defining the size of an array. So, what I understood is that every time there is an input I have to check if its the desired kind of output required or not.
> Is that so???

@abirbhattacharya82 Yes, you need to validate every input you take from the user as you should never trust the user. It's to ensure you are getting the input you expect and not anything else.

**Comment by abirbhattacharya82** [comment]
Ok got it. Thanks for letting me know this.

**Pull request closed without merging**
